# Generated by Django 6.0.6 on 2026-07-24 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atix', '0004_rename_update_at_product_updated_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_verified',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
