# Generated by Django 6.0.6 on 2026-07-26 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atix', '0005_user_is_verified_user_otp_user_otp_created_at'),
    ]

    operations = [
        migrations.CreateModel(
            name='Coupon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(help_text='e.g. SALE20', max_length=20, unique=True)),
                ('discount_type', models.CharField(choices=[('percentage', 'Percentage %'), ('fixed', 'Fixed Amount ₹')], default='percentage', max_length=20)),
                ('discount_value', models.DecimalField(decimal_places=2, help_text='20 = 20% or ₹20', max_digits=6)),
                ('min_order', models.DecimalField(decimal_places=2, default=0, help_text='Minimum cart value', max_digits=8)),
                ('max_uses', models.PositiveIntegerField(default=100)),
                ('used_count', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
