# Generated by Django 6.0.6 on 2026-08-01 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atix', '0008_user_password_changed_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='gender',
            field=models.CharField(choices=[('men', 'Men'), ('women', 'Women'), ('unisex', 'Unisex')], default='unisex', max_length=10),
        ),
    ]
